### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by SteveTeece** [MadalinCernat/Eventus#1]
This sounds like an interesting project.  Is there anything I can do to help?

**Comment by MadalinCernat** [comment]
Hello and thank you.

Definitely. The first step is the database design. 
If you want, you can go ahead and create some tables in the SQL project.

**Comment by SteveTeece** [comment]
What info do you want stored?

**Comment by MadalinCernat** [comment]
I can think about 4 tables right now, for the beginning: Event, Comment, EventInvitation, EventRequest.

The columns for events are in the readme file.
If needed, you can add anything you wish.
