### ISSUE TITLE
SqlCrud class is too big

### ISSUE THREAD

**Issue by MadalinCernat** [MadalinCernat/Eventus#14]
I think about separating SqlCrud in more classes (e.g. EventCrud, InvitationCrud)

**Comment by SrgjanX** [comment]
As I was working on this, personally, I would seperate every #region in different class file, whether is partial class dont matter.
If you want, I can do it, assign the item to me.

**Comment by MadalinCernat** [comment]
Hello! You can do it if you want. Thanks for your interest and contributions.
