### ISSUE TITLE
SQL CRUD & OTHER ISSUES

### ISSUE THREAD

**Issue by MadalinCernat** [MadalinCernat/Eventus#3]
### ISSUES:
1. we don't have a field for activity in the Invitation table yet
2. we need a field in the Event table that stores if the event is archived or not, and one that stores if the event is active or not (its date passed or not)
3. will the events be automatically archived after some days? probably yes. still thinking of that.

#### MAKE STORED PROCEDURES FOR: 
GET:
- [x] all events
- [x] event by event id
- [x] events created by a user
- [x] invitations for a user
- [x] invitations sent by a user
- [x] requests for an event
- [x] requests sent by a user
- [x] all places

INSERT:
- [x] event
- [x] invitation
- [x] request
- [x] city
- [x] user city
- [x] place
- [x] event participant
- [x] comment

UPDATE:
- [x] event
- [x] invitation status (Accepted)
- [x] invitation IsActive field(for the ability to cancel it). Note: see issue 1
- [x] event IsActive field(in the app it will be updated automatically when the date passes). Note: see issue 2
- [x] event IsArchived field(that will allow users archive their events so they don't show on the explore page). Note: see issue 3
- [x] comment (probably editing comments won't be available in V1 but it's good to have it there)

**Comment by hartkemd** [comment]
I can work on this issue, if you want to assign it to me.
